import type { Listing } from '@/types/listings'

export const mockListings: Listing[] = [
  {
    id: '1',
    referenceNumber: 'KRB-001',
    slug: 'bmw-320i-m-sport-2021-southampton',
    title: 'BMW 320i M Sport Auto',
    description: `An exceptional example of the BMW 3 Series in M Sport specification. Full BMW dealer service history, one previous owner, and presented in Alpine White with a black leather interior. This car has been meticulously maintained and represents an excellent opportunity to own a premium saloon at a competitive price.\n\nEquipped with the full M Sport package including 18-inch M Sport alloys, adaptive LED headlights, and the upgraded M Sport suspension. The latest iDrive 8 infotainment system with wireless Apple CarPlay and Android Auto.\n\nFirst registered April 2021. Remaining BMW warranty until April 2025. ULEZ compliant.`,
    makeName: 'BMW',
    modelName: '3 Series',
    variantName: '320i M Sport',
    year: 2021,
    registration: 'YD21 KPX',
    price: 2699500, // £26,995
    priceOno: false,
    priceRating: 'good_deal',
    mileage: 28400,
    fuelType: 'petrol',
    transmission: 'automatic',
    bodyType: 'saloon',
    doors: 4,
    seats: 5,
    engineSizeDisplay: '2.0L',
    powerBhp: 184,
    colourExterior: 'Alpine White',
    serviceHistory: 'full',
    previousOwners: 1,
    motExpiry: '2025-04-15',
    conditionGrade: 'excellent',
    features: ['Heated seats', 'Apple CarPlay', 'Parking sensors', 'Reversing camera', 'Adaptive cruise control', 'Lane departure warning', 'M Sport package', 'LED headlights', 'Sunroof'],
    ulezCompliant: true,
    sellerType: 'dealer',
    dealer: {
      id: 'd1',
      slug: 'premium-autos-southampton',
      businessName: 'Premium Autos Southampton',
      city: 'Southampton',
      county: 'Hampshire',
      postcode: 'SO14 1AA',
      phone: '023 8000 1234',
      email: 'sales@premiumautos.co.uk',
      rating: 4.8,
      reviewCount: 147,
      verified: true,
      tier: 'pro',
    },
    media: [
      { id: 'm1', url: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200', thumbnailUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=400', isPrimary: true, order: 1 },
      { id: 'm2', url: 'https://images.unsplash.com/photo-1617469767904-ff44c4f7d8c9?w=1200', thumbnailUrl: 'https://images.unsplash.com/photo-1617469767904-ff44c4f7d8c9?w=400', isPrimary: false, order: 2 },
    ],
    motHistory: [
      { date: '2024-04-10', result: 'pass', mileage: 24200, advisories: ['Tyre wear (advisory)'], failures: [], expiryDate: '2025-04-15' },
      { date: '2023-04-12', result: 'pass', mileage: 16800, advisories: [], failures: [] },
    ],
    postcode: 'SO14 1AA',
    city: 'Southampton',
    county: 'Hampshire',
    deliveryAvailable: true,
    tier: 'enhanced',
    status: 'active',
    publishedAt: '2026-06-05T09:00:00Z',
    expiresAt: '2026-07-05T09:00:00Z',
  },
  {
    id: '2',
    referenceNumber: 'KRB-002',
    slug: 'volkswagen-golf-gti-2022-guildford',
    title: 'Volkswagen Golf GTI DSG',
    description: `The definitive hot hatch in pristine condition. Tornado Red with black Dinamica/leather sport seats. This Golf GTI has covered just 19,200 miles and has a full VW service history. Both sets of keys present.\n\nFeaturing the Digital Cockpit Pro, IQ.DRIVE safety systems, and the powerful 2.0 TSI 245bhp engine mated to the 7-speed DSG gearbox. Runs perfectly and has been a joy to own.`,
    makeName: 'Volkswagen',
    modelName: 'Golf',
    variantName: 'GTI DSG',
    year: 2022,
    registration: 'EO22 WVR',
    price: 2849500, // £28,495
    priceOno: true,
    priceRating: 'fair',
    mileage: 19200,
    fuelType: 'petrol',
    transmission: 'automatic',
    bodyType: 'hatchback',
    doors: 5,
    seats: 5,
    engineSizeDisplay: '2.0L TSI',
    powerBhp: 245,
    colourExterior: 'Tornado Red',
    serviceHistory: 'full',
    previousOwners: 1,
    motExpiry: '2025-03-20',
    conditionGrade: 'excellent',
    features: ['Digital Cockpit Pro', 'IQ.DRIVE pack', 'Parking sensors', 'Adaptive cruise control', 'Wireless Apple CarPlay', 'Sport seats', 'DCC adaptive chassis', '18-inch Pretoria alloys'],
    ulezCompliant: true,
    sellerType: 'private',
    media: [
      { id: 'm3', url: 'https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=1200', thumbnailUrl: 'https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=400', isPrimary: true, order: 1 },
    ],
    postcode: 'GU1 3AF',
    city: 'Guildford',
    county: 'Surrey',
    deliveryAvailable: false,
    tier: 'standard',
    status: 'active',
    publishedAt: '2026-06-07T14:00:00Z',
    expiresAt: '2026-07-07T14:00:00Z',
  },
  {
    id: '3',
    referenceNumber: 'KRB-003',
    slug: 'porsche-911-carrera-2019-london',
    title: 'Porsche 911 Carrera S PDK',
    description: `A stunning 991.2 Carrera S in GT Silver Metallic with the Sports Chrono package and PASM. Finished in GT Silver Metallic over a black leather interior with brushed aluminium trim.\n\nSuperbly specified with Sport Exhaust, LED Matrix headlights, 20-inch Carrera S alloys, Bose Surround Sound, and the full PCM infotainment package. Full Porsche Centre service history throughout.`,
    makeName: 'Porsche',
    modelName: '911',
    variantName: 'Carrera S PDK',
    year: 2019,
    registration: 'LK19 WPR',
    price: 8499500, // £84,995
    priceOno: false,
    priceRating: 'good_deal',
    mileage: 22100,
    fuelType: 'petrol',
    transmission: 'automatic',
    bodyType: 'coupe',
    doors: 2,
    seats: 4,
    engineSizeDisplay: '3.0L Twin Turbo',
    powerBhp: 450,
    colourExterior: 'GT Silver Metallic',
    serviceHistory: 'full',
    previousOwners: 1,
    motExpiry: '2025-06-01',
    conditionGrade: 'excellent',
    features: ['Sports Chrono', 'PASM', 'Sport Exhaust', 'LED Matrix headlights', 'Bose Surround Sound', 'PCM Navigation', 'Heated seats', 'Lane change assist', '20-inch alloys'],
    ulezCompliant: true,
    sellerType: 'dealer',
    dealer: {
      id: 'd2',
      slug: 'select-sports-cars-london',
      businessName: 'Select Sports Cars',
      city: 'London',
      county: 'Greater London',
      postcode: 'SW6 3AE',
      phone: '020 7000 9876',
      email: 'info@selectsportscars.co.uk',
      rating: 4.9,
      reviewCount: 312,
      verified: true,
      tier: 'enterprise',
    },
    media: [
      { id: 'm5', url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200', thumbnailUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=400', isPrimary: true, order: 1 },
    ],
    postcode: 'SW6 3AE',
    city: 'London',
    county: 'Greater London',
    deliveryAvailable: true,
    tier: 'premium',
    status: 'active',
    publishedAt: '2026-06-08T10:00:00Z',
    expiresAt: '2026-07-08T10:00:00Z',
  },
  {
    id: '4',
    referenceNumber: 'KRB-004',
    slug: 'toyota-land-cruiser-2020-bristol',
    title: 'Toyota Land Cruiser Invincible D-4D',
    description: `A genuinely exceptional Land Cruiser — properly maintained, properly specified, and properly ready for anything. Seven seats, full Toyota service history, and a comprehensive specification including the JBL audio system, panoramic roof, and 360-degree camera.\n\nThis is a car that will comfortably cover 200,000 miles with the correct maintenance. All service intervals met on time at Toyota dealers. No expense spared on care.`,
    makeName: 'Toyota',
    modelName: 'Land Cruiser',
    variantName: 'Invincible D-4D',
    year: 2020,
    registration: 'BF20 LCR',
    price: 5499500, // £54,995
    priceOno: false,
    priceRating: 'fair',
    mileage: 61000,
    fuelType: 'diesel',
    transmission: 'automatic',
    bodyType: 'suv',
    doors: 5,
    seats: 7,
    engineSizeDisplay: '2.8L D-4D',
    powerBhp: 204,
    colourExterior: 'Midnight Black',
    serviceHistory: 'full',
    previousOwners: 2,
    motExpiry: '2025-07-20',
    conditionGrade: 'good',
    features: ['7 seats', 'Panoramic roof', 'JBL audio', '360-degree camera', 'Crawl control', 'Multi-terrain select', 'Heated + ventilated seats', 'HDD navigation', 'Head-up display'],
    ulezCompliant: false,
    sellerType: 'dealer',
    dealer: {
      id: 'd3',
      slug: 'bristol-4x4-centre',
      businessName: 'Bristol 4x4 Centre',
      city: 'Bristol',
      county: 'Bristol',
      postcode: 'BS1 4ST',
      phone: '0117 000 5555',
      email: 'sales@bristol4x4.co.uk',
      rating: 4.6,
      reviewCount: 89,
      verified: true,
      tier: 'growth',
    },
    media: [
      { id: 'm7', url: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200', thumbnailUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=400', isPrimary: true, order: 1 },
    ],
    postcode: 'BS1 4ST',
    city: 'Bristol',
    county: 'Bristol',
    deliveryAvailable: true,
    tier: 'enhanced',
    status: 'active',
    publishedAt: '2026-06-03T08:00:00Z',
    expiresAt: '2026-07-03T08:00:00Z',
  },
  {
    id: '5',
    referenceNumber: 'KRB-005',
    slug: 'mazda-mx5-rf-2021-winchester',
    title: 'Mazda MX-5 RF 2.0 Sport Tech',
    description: `The retractable fastback MX-5 RF in Soul Red Crystal — genuinely one of the best-looking cars on the road. Sport Tech specification with Bose sound system, Bilstein dampers, and Recaro seats.\n\nOnly 14,800 miles from new. One private owner from new. Full Mazda dealer service history. This car drives as well as it looks.`,
    makeName: 'Mazda',
    modelName: 'MX-5',
    variantName: 'RF 2.0 Sport Tech',
    year: 2021,
    registration: 'YC21 MXR',
    price: 2699500, // £26,995
    priceOno: false,
    priceRating: 'great_deal',
    mileage: 14800,
    fuelType: 'petrol',
    transmission: 'manual',
    bodyType: 'convertible',
    doors: 2,
    seats: 2,
    engineSizeDisplay: '2.0L',
    powerBhp: 184,
    colourExterior: 'Soul Red Crystal',
    serviceHistory: 'full',
    previousOwners: 1,
    motExpiry: '2025-08-10',
    conditionGrade: 'excellent',
    features: ['Recaro seats', 'Bilstein dampers', 'Bose sound system', 'Heated seats', 'Leather trim', 'Reversing camera', 'Sat nav', 'Keyless entry'],
    ulezCompliant: true,
    sellerType: 'private',
    media: [
      { id: 'm9', url: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=1200', thumbnailUrl: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=400', isPrimary: true, order: 1 },
    ],
    motHistory: [
      { date: '2024-08-05', result: 'pass', mileage: 12400, advisories: [], failures: [], expiryDate: '2025-08-10' },
    ],
    postcode: 'SO23 8AA',
    city: 'Winchester',
    county: 'Hampshire',
    deliveryAvailable: false,
    tier: 'standard',
    status: 'active',
    publishedAt: '2026-06-09T11:00:00Z',
    expiresAt: '2026-07-09T11:00:00Z',
  },
  {
    id: '6',
    referenceNumber: 'KRB-006',
    slug: 'mercedes-c220d-amg-line-2023-reading',
    title: 'Mercedes C 220 d AMG Line Auto',
    description: `A nearly-new Mercedes C-Class in Obsidian Black, loaded with AMG Line specification. This car has covered just 8,200 miles and is still within the Mercedes two-year warranty. Presented in immaculate condition throughout.\n\nFull digital interior with the 11.9-inch MBUX touchscreen, AMG Line interior with sport seats, heated steering wheel, and the panoramic glass sunroof.`,
    makeName: 'Mercedes',
    modelName: 'C-Class',
    variantName: 'C 220 d AMG Line',
    year: 2023,
    registration: 'HK73 CMW',
    price: 3799500, // £37,995
    priceOno: false,
    priceRating: 'good_deal',
    mileage: 8200,
    fuelType: 'diesel',
    transmission: 'automatic',
    bodyType: 'saloon',
    doors: 4,
    seats: 5,
    engineSizeDisplay: '2.0L CDI',
    powerBhp: 200,
    colourExterior: 'Obsidian Black',
    serviceHistory: 'full',
    previousOwners: 1,
    motExpiry: '2026-09-01',
    conditionGrade: 'excellent',
    features: ['MBUX 11.9" screen', 'AMG Line exterior', 'AMG Line interior', 'Panoramic sunroof', 'Heated seats', 'Heated steering wheel', 'Wireless Apple CarPlay', 'Parking package', 'Ambient lighting'],
    ulezCompliant: true,
    sellerType: 'dealer',
    dealer: {
      id: 'd4',
      slug: 'thames-valley-motors',
      businessName: 'Thames Valley Motors',
      city: 'Reading',
      county: 'Berkshire',
      postcode: 'RG1 3EA',
      phone: '0118 000 7788',
      email: 'sales@tvmotors.co.uk',
      rating: 4.7,
      reviewCount: 203,
      verified: true,
      tier: 'pro',
    },
    media: [
      { id: 'm11', url: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=1200', thumbnailUrl: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=400', isPrimary: true, order: 1 },
    ],
    postcode: 'RG1 3EA',
    city: 'Reading',
    county: 'Berkshire',
    deliveryAvailable: true,
    tier: 'enhanced',
    status: 'active',
    publishedAt: '2026-06-10T08:00:00Z',
    expiresAt: '2026-07-10T08:00:00Z',
  },
]

export function getListingBySlug(slug: string): Listing | undefined {
  return mockListings.find(l => l.slug === slug)
}

export function searchListings(query?: string, filters?: Record<string, string>): Listing[] {
  let results = [...mockListings]

  if (query) {
    const q = query.toLowerCase()
    results = results.filter(l =>
      l.title.toLowerCase().includes(q) ||
      l.makeName.toLowerCase().includes(q) ||
      l.modelName.toLowerCase().includes(q)
    )
  }

  if (filters?.make) {
    results = results.filter(l => l.makeName.toLowerCase() === filters.make!.toLowerCase())
  }
  if (filters?.bodyType) {
    results = results.filter(l => l.bodyType === filters.bodyType)
  }
  if (filters?.fuelType) {
    results = results.filter(l => l.fuelType === filters.fuelType)
  }
  if (filters?.transmission) {
    results = results.filter(l => l.transmission === filters.transmission)
  }
  if (filters?.maxPrice) {
    results = results.filter(l => l.price <= parseInt(filters.maxPrice!) * 100)
  }

  return results
}
