name = "selectus-motors-web"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXT_PUBLIC_BASE_URL = "https://selectusmotors.com"
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_live_51TibFXFNgPGWyXchk7laT4uVikfOh7keKP5zCqkHrEeOcLRfSXKDHC6hULxEj2NxXmjCsIokAL7ulTM4FJIOvghB00CLeSaDu6"
NEXT_PUBLIC_GA_ID = "G-MFCDLJ52QL"
NEXT_PUBLIC_CLARITY_ID = "x7v8fg28yj"
NEXT_PUBLIC_SEARCH_CONSOLE_ID = ""
NEXT_PUBLIC_SUPABASE_URL = "https://ymxueqlbnqxzamxgomhx.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_TTWUUkA0hGF8MdK3BQRxIg_0CC71ny6"
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_test_cG9ldGljLWdsb3d3b3JtLTY4LmNsZXJrLmFjY291bnRzLmRldiQ"
NEXT_PUBLIC_CLERK_SIGN_IN_URL = "/sign-in"
NEXT_PUBLIC_CLERK_SIGN_UP_URL = "/sign-up"
NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL = "/dashboard"
NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL = "/dashboard"
