name = "selectus-motors-web"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXT_PUBLIC_BASE_URL = "https://selectusmotors.com"
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_test_51TibFoFVFkk5AvROr1RRr3nz5RgLWZfdZRqsx2d1WL4vwoCadm8UV5nt1UV81mRWZbVo8AAx7EvW0ttyn5hEFD4L005Mz9PxSc"
# Analytics — fill in once accounts are set up
NEXT_PUBLIC_GA_ID = "G-MFCDLJ52QL"
NEXT_PUBLIC_CLARITY_ID = "x7v8fg28yj"
NEXT_PUBLIC_SEARCH_CONSOLE_ID = ""
